### ISSUE TITLE
Use faster JSON library

### ISSUE THREAD

**Issue by HexwellC** [foxcpp/Hexicord#5]
Basicly we have two good options: [RapidJSON](https://github.com/miloyip/rapidjson/) as the fastest library and [taocpp/json](https://github.com/taocpp/json) as the fast and most conformant one. [There's others but they should be discussed as well](https://github.com/miloyip/nativejson-benchmark).
Performance is the main goal of Hexicord library. nlohman JSON library is good enough as well, but sometimes we might want to go _even faster_. The problem is that RapidJSON library is a little bit... Weird. The usage of RapidJSON should be discussed as much as possible. Until then, we're good to go with nlohman's library. 
So. The only situation when we'll _definitely_ move to RapidJSON is reflection in C++. Or, maybe if we'll find a better way to create wrappers for all those JSON stuff that is exposed to user. Think about it: writing separate toJSON and fromJSON methods or even just overriding operators for _each_ Discord object is not the best idea.

**Comment by foxcpp** [comment]
### My results for RapidJSON/nlohmann's JSON comparsion.

#### Environment
**OS:** Archlinux x86_64
**CPU:**  Intel Core i5-4460 @ 3.2 Ghz
**Compiler:** GCC 7.1.1 20170630
As root user with nice value set to -20.

#### Benchmarked code
For nlohmann JSON:
```cpp
#include <string>
#include <chrono>
#include <iostream>
#include <iterator>
#include <fstream>
#include <vector>
#include <json.hpp>

int main(int argc, char** argv) {
    std::ifstream file("test.json");

    std::string fileStr
        {
         std::istreambuf_iterator<char>(file),
         std::istreambuf_iterator<char>()
        };


    auto start = std::chrono::steady_clock::now();

    int c = std::stoi(std::string(argv[1]));
    while (c --> 0) {
        nlohmann::json::parse(fileStr);
    }

    auto end = std::chrono::steady_clock::now();

    std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " msec\n";
}
```
**Note:** Due to nlohmann's library architecture this also includes allocation/copy overhead. Which can be high due to used JSON (see below).

For RapidJSON:
```cpp
#include <string>
#include <chrono>
#include <iostream>
#include <iterator>
#include <fstream>
#include <vector>
#include <rapidjson/document.h>

int main(int argc, char** argv) {
    std::ifstream file("test.json");

    std::string fileStr
        {
         std::istreambuf_iterator<char>(file),
         std::istreambuf_iterator<char>()
        };


    auto start = std::chrono::steady_clock::now();

    int c = std::stoi(std::string(argv[1]));
    rapidjson::Document document;
    while (c --> 0) {
        document.Parse(fileStr.data());
    }

    auto end = std::chrono::steady_clock::now();

    std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << " msec\n";
}
```
#### Compilation commands
For both:
```
# g++ -std=c++11 -O2 -I . -O test
```

#### Used test.json
https://raw.githubusercontent.com/zemirco/sf-city-lots-json/master/citylots.json
**Size:** 181 MiB.

#### Measurement process
As you can see above this code runs parse function `c` times. So I run it like this (twice):
```
# ./test 10
```
and divide result by 10 to get average.

#### Results
##### nlohmann's JSON
First run: `39431 msec` (avg per iteration is `3941.1 ms`)
Second run: `39504 msec` (avg per iteration is `3950.4 ms`)

Memory usage (values are not percise since I don't know how to measure correctly): 
* average: `600 MB`
* peak: `987 MB`

##### RapidJSON
First run: `4431 msec` (avg per iteration is `443.1 ms`)
Second run: `4330 msec` (avg per iteration is `433.0 ms`)

Memory usage (values are not percise since I don't know how to measure correctly):
* average: `1 GB`
* peak: `2.5 GB`

#### Conclusion

RapidJSON is 10 times faster, but also have bigger memory footprint.
However bots will unlikely have to process such big JSON's. Thus I think that
nlohmann's JSON performance is enough. It's better to have good interface
since we expose all JSON to users of library.

**Comment by foxcpp** [comment]
RapidJSON will be used in 2.0.

**Comment by foxcpp** [comment]
JSON parsing/generation overhead is REALLY small. There is no reason to change JSON library at all. Closing.

**Comment by HexwellC** [comment]
@foxcpp JSON parsing overhead depends on the size of a JSON message. I still think it should be thrown in a long shelf and implemented one sunny day by somebody.

**Comment by foxcpp** [comment]
Give me very popular bot that uses Hexicord and I will probably change my decision.
